  
language: java
jdk:
  - oraclejdk11
  
sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.29.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  
before_script:
  - docker-compose up -d --build
    
after_script:
  - docker-compose down
